kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cnpg
nodes:
- role: control-plane
- role: worker
  labels:
    workload: postgres
- role: worker
  labels:
    workload: postgres
- role: worker
  labels:
    workload: postgres
- role: worker
  labels:
    workload: pgbench
